export class hrmsapplicantmaster {
public applicantiddesc :string;public applicantid :number;public applicationdate :Date;public applicantcode :string;public applicantname :string;public title :string;public jobrole :number;public jobroledesc :string;public department :number;public departmentdesc :string;public mobile :string;public email :string;public otherphone :string;public dob :Date;public gender :string;public genderdesc :string;public maritalstatus :string;public maritalstatusdesc :string;public source :string;public sourcedesc :string;public sourcereferences :string;public highestqualification :string;public highestqualificationdesc :string;public suitableposition :number;public suitablepositiondesc :string;public relatedexperience :number;public totalexperience :number;public internationalexperience :string;public currentsalarycurrency :string;public currentsalarycurrencydesc :string;public currentsalary :number;public expectedsalarycurrency :string;public expectedsalarycurrencydesc :string;public expectedfromsalary :number;public expectedtosalary :number;public noticeperiod :number;public passportnumber :string;public issuecountry :number;public issuecountrydesc :string;public issuedate :Date;public expirydate :Date;public nationality :string;public nationalitydesc :string;public locationpreference :number;public locationpreferencedesc :string;public address1 :string;public address2 :string;public countryid :number;public countryiddesc :string;public stateid :number;public stateiddesc :string;public cityid :number;public cityiddesc :string;public pincode :string;public reference1 :string;public reference1mobile :string;public reference1email :string;public reference2 :string;public reference2mobile :string;public reference2email :string;public attachment :string;public customfield :string;public remarks :string;public rejectiontill :Date;public status :string;public DeletedhrmsinterviewscheduleIDs :string;public DeletedhrmsapplicantofferIDs :string;public DeletedhrmsapplicantcareerIDs :string;public DeletedhrmsapplicanteducationIDs :string;public DeletedhrmsapplicantskillIDs :string;public DeletedhrmsmprapplicantIDs :string;
constructor() {}
}
export interface IhrmsapplicantmasterResponse {
total: number;
results: hrmsapplicantmaster[];
}

