export class hlpticket {
    public ticketiddesc: string; public ticketid: number; public sourcefield: string; public sourcefielddesc: string; public sourcereference: number; public branchid: number; public branchiddesc: string; public departmentid: number; public departmentiddesc: string; public requestortype: string; public requestortypedesc: string; public requestor: number; public requestordesc: string; public item: string; public ticketdate: Date; public incidentdate: Date; public incidenttime: string; public incidentduration: string; public duedate: Date; public assignedto: string; public tickettype: string; public tickettypedesc: string; public priority: string; public prioritydesc: string; public criticality: string; public criticalitydesc: string; public impact: string; public impactdesc: string; public risk: string; public riskdesc: string; public sla: number; public sladesc: string; public slabreached: boolean; public source: string; public sourcedesc: string; public ticketreference: string; public category: number; public categorydesc: string; public subcategory: number; public subcategorydesc: string; public tags: string; public subject: string; public ticketdetails: string; public impacteditems: string; public impactedservices: string; public impactedproducts: string; public impactdetails: string; public remarks: string; public stage: string; public stagedesc: string; public completedby: number; public completedbydesc: string; public linkedtickets: string; public rca: number; public rcadesc: string; public rcadetails: string; public solution: number; public solutiondesc: string; public solutiondetails: string; public solutiongivenon: Date; public startdate: Date; public completeddate: Date; public lessonslearned: string; public history: string; public customfield: string; public attachment: string; public status: string; public Deleted_hlpticketdetail_IDs: string; public Deleted_hlpplannedaction_IDs: string;
    constructor() { }
}
export interface IhlpticketResponse {
    total: number;
    results: hlpticket[];
}

