export class lmsmaster {
    public branchid: number; public branchiddesc: string; public branchlocationid: number; public branchlocationiddesc: string; public leadiddesc: string; public leadid: number; public iscorporate: string; public iscorporatedesc: string; public companyname: string; public leadowner: number; public leadownerdesc: string; public firstname: string; public lastname: string; public emailid: string; public companytypeid: number; public companytypeiddesc: string; public categoryid: number; public categoryiddesc: string; public subcategoryid: number; public subcategoryiddesc: string; public groupname: string; public groupnamedesc: string; public salutation: string; public salutationdesc: string; public designation: number; public designationdesc: string; public contactno: string; public address: string; public website: string; public datecreated: Date; public leadtype: string; public leadtypedesc: string; public leadsource: string; public leadsourcedesc: string; public leaddate: Date; public nextcontactduedate: Date; public campaignid: number; public campaigniddesc: string; public rating: number; public segment: string; public segmentdesc: string; public businessvertical: string; public businessverticaldesc: string; public revenue: string; public revenuedesc: string; public employees: string; public employeesdesc: string; public language: string; public languagedesc: string; public crosssellopportunity: boolean; public successrate: number; public businessvalue: number; public subscribedemail: boolean; public shippingaddress: string; public billingaddress: string; public photo: string; public thumbnail: string; public paymentterms: string; public paymenttermsdesc: string; public socialmedia: string; public leadstatus: string; public leadstatusdesc: string; public notes: string; public customfield: string; public attachment: string; public status: string; public Deleted_lmsopportunity_IDs: string; public Deleted_lmscall_IDs: string; public Deleted_lmscorporatesecondarycontact_IDs: string;
    constructor() { }
}
export interface IlmsmasterResponse {
    total: number;
    results: lmsmaster[];
}

