export class pmsproperty {
public propertyiddesc :string;public propertyid :number;public propertycode :string;public title :string;public details :string;public propertytype :string;public propertytypedesc :string;public thumbnail :string;public datecreated :Date;public rating :number;public metatag :string;public address1 :string;public address2 :string;public countryid :number;public countryiddesc :string;public stateid :number;public stateiddesc :string;public cityid :number;public cityiddesc :string;public pincode :string;public ownerid :number;public owneriddesc :string;public bankaccountid :number;public bankaccountiddesc :string;public currency :string;public currencydesc :string;public reserveamount :number;public responsibleid :number;public responsibleiddesc :string;public yearbuilt :number;public propertylife :number;public latitude :string;public longitude :string;public contactperson :string;public phone1 :string;public phone2 :string;public email :string;public website :string;public unitno :string;public unittype :string;public unittypedesc :string;public sqft :number;public sizedetails :string;public rooms :string;public beds :string;public bedsdesc :string;public baths :string;public bathsdesc :string;public rent :number;public notes :string;public assignowner :boolean;public ownership :string;public ownershipdesc :string;public ownernotes :string;public occupancytype :string;public occupancytypedesc :string;public deposit :number;public advance :number;public invoiceday :number;public hasfirstrentcommission :boolean;public firstrentcommissiontype :string;public firstrentcommissiontypedesc :string;public firstrentcommission :number;public hasrentcommission :boolean;public rentcommissiontype :string;public rentcommissiontypedesc :string;public rentcommission :number;public hasrenewalfee :boolean;public renewalfeetype :string;public renewalfeetypedesc :string;public renewalfee :number;public hasservicefee :boolean;public servicefeetype :string;public servicefeetypedesc :string;public servicefee :number;public facebook :string;public googleplus :string;public twitter :string;public instagram :string;public pinterest :string;public linkedin :string;public status :string;public customfield :string;public attachment :string;public DeletedpmspropertyassetIDs :string;public DeletedpmspropertyimageIDs :string;public DeletedpmspropertyopexdetailIDs :string;public DeletedpmspropertycontactIDs :string;public DeletedpmsleaseIDs :string;public DeletedpmspropertyunitIDs :string;public DeletedpmsworkorderIDs :string;public DeletedpmspropertydocumentIDs :string;
constructor() {}
}
export interface IpmspropertyResponse {
total: number;
results: pmsproperty[];
}

