export class prjprojectmaster {
public projectiddesc :string;public projectid :number;public sourcefield :string;public sourcereference :number;public projectcode :string;public projectname :string;public departmentid :number;public customerid :number;public customeriddesc :string;public salesorderid :number;public briefdescription :string;public projectscope :string;public thumbnail :string;public projectmanager :number;public projectmanagerdesc :string;public startdate :Date;public enddate :Date;public progressrate :number;public lastupdateddate :Date;public actualstartdate :Date;public projectedenddate :Date;public completeddate :Date;public closeddate :Date;public lastreviseddate :Date;public projecttype :string;public projecttypedesc :string;public priority :string;public prioritydesc :string;public projectphase :string;public projectphasedesc :string;public projectstatus :string;public projectstatusdesc :string;public currency :string;public currencydesc :string;public totalbudgetamount :number;public feedbacktags :string;public budgetmaterialcost :number;public budgetlabourcost :number;public actualmaterialcost :number;public actuallabourcost :number;public materialbudgetremaining :number;public totalbudgetremaining :number;public totalhoursestimated :string;public totalactualhours :string;public notes :string;public costcenterid :number;public customfield :string;public attachment :string;public status :string;public DeletedprjprojectdeliverableIDs :string;public DeletedprjexpenseIDs :string;public DeletedprjprojecttaskIDs :string;public DeletedbofactIDs :string;public DeletedprjprojectchangeIDs :string;public DeletedboremindermasterIDs :string;public DeletedprjprojectteammemberIDs :string;public DeletedprjprojectverificationIDs :string;public DeletedprjtimecardIDs :string;public DeletedprjdocumentIDs :string;public DeletedprjprojectbillingIDs :string;public DeletedprjprojectobjectiveIDs :string;public DeletedprjdailystandupIDs :string;public DeletedprjchangerequestIDs :string;public DeletedprjreleaseIDs :string;public DeletedproprocessgapIDs :string;public DeletedbouserIDs :string;public DeletedprjprojectoutputIDs :string;public DeletedprjprojectrequirementIDs :string;
constructor() {}
}
export interface IprjprojectmasterResponse {
total: number;
results: prjprojectmaster[];
}

