export class flminspection {
    public inspectionid: number; public vehicleid: number; public description: string; public odometerreading: number; public odometerreadingremarks: string; public interiorcleanliness: string; public interiorcleanlinessdesc: string; public interiorcleanlinessremarks: string; public engine: string; public enginedesc: string; public engineremarks: string; public oillife: string; public oillifedesc: string; public oilliferemarks: string; public fuellevel: string; public fuelleveldesc: string; public fuellevelremarks: string; public transmission: string; public transmissiondesc: string; public transmissionremarks: string; public clutch: string; public clutchdesc: string; public clutchremarks: string; public steeringmechanism: string; public steeringmechanismdesc: string; public steeringmechanismremarks: string; public horn: string; public horndesc: string; public hornremarks: string; public windshield: string; public windshielddesc: string; public windshieldremarks: string; public wipers: string; public wipersdesc: string; public wipersremarks: string; public washers: string; public washersdesc: string; public washersremarks: string; public rearvisionmirrors: string; public rearvisionmirrorsdesc: string; public rearvisionmirrorsremarks: string; public lighting: string; public lightingdesc: string; public lightingremarks: string; public reflector: string; public reflectordesc: string; public reflectorremarks: string; public parkingbrake: string; public parkingbrakedesc: string; public parkingbrakeremarks: string; public servicebrake: string; public servicebrakedesc: string; public servicebrakeremarks: string; public airlines: string; public airlinesdesc: string; public airlinesremarks: string; public couplingdevice: string; public couplingdevicedesc: string; public couplingdeviceremarks: string; public tyres: string; public tyresdesc: string; public tyresremarks: string; public wheels: string; public wheelsdesc: string; public wheelsremarks: string; public rims: string; public rimsdesc: string; public rimsremarks: string; public emergencyequipment: string; public emergencyequipmentdesc: string; public emergencyequipmentremarks: string; public vehiclecondition: string; public vehicleconditiondesc: string; public remarks: string; public drivernotes: string; public driversignature: string; public attachment: string; public status: string;
    constructor() { }
}
export interface IflminspectionResponse {
    total: number;
    results: flminspection[];
}

