export class legalcase {
public caseiddesc :string;public caseid :number;public casecode :string;public casenumber :string;public internalreferencenumber :string;public courtid :number;public courtiddesc :string;public petitiontype :string;public petitiontypedesc :string;public customerid :number;public customeriddesc :string;public customerposition :string;public customerpositiondesc :string;public opponentid :number;public opponentiddesc :string;public opponentposition :string;public opponentpositiondesc :string;public casedate :Date;public casereceiveddate :Date;public duedate :Date;public noticedate :Date;public fileddate :Date;public previouscasenumber :number;public previouscasenumberdesc :string;public caseowner :string;public requestedby :number;public requestedbydesc :string;public assignedby :number;public assignedbydesc :string;public casemode :number;public casemodedesc :string;public casetype :number;public casetypedesc :string;public casesubtype :number;public casesubtypedesc :string;public casetitle :string;public casedetails :string;public firstdateofhearing :Date;public date1 :Date;public notes1 :string;public date2 :Date;public notes2 :string;public date3 :Date;public notes3 :string;public category :string;public categorydesc :string;public nature :string;public naturedesc :string;public complexity :string;public complexitydesc :string;public priority :string;public prioritydesc :string;public timeline :string;public timelinedesc :string;public amountinvolved :number;public judgementvalue :number;public amountreceived :number;public customfield :string;public attachment :string;public judgementdate :Date;public judgementinfavour :boolean;public judgementoutcome :string;public judgementoutcomedesc :string;public judgementdescription :string;public actiontobetaken :string;public actionby :number;public actionbydesc :string;public actionimplemented :boolean;public contestfurther :boolean;public closeddate :Date;public casestage :string;public casestagedesc :string;public casestatus :string;public casestatusdesc :string;public lawyer :number;public lawyerdesc :string;public lastprocess :number;public currentprocess :number;public nexthearingdate :Date;public casetag :string;public notes :string;public status :string;public DeletedlegalcaselawyerIDs :string;public DeletedlegalcasepartydetailIDs :string;public DeletedlegalcaseprocessdetailIDs :string;public DeletedlegalcaseinterimorderIDs :string;public DeletedlegalcasereferredcaseIDs :string;public DeletedlegalcasekbIDs :string;public DeletedlegaltaskmasterIDs :string;public DeletedboexpenseIDs :string;public DeletedlegalfreenoteIDs :string;public DeletedlegalcommunicationdetailIDs :string;public DeletedlegalcaseagainstemployeeIDs :string;public DeletedlegalcasehearingIDs :string;
constructor() {}
}
export interface IlegalcaseResponse {
total: number;
results: legalcase[];
}

