export class bocompanymaster {
    public companyiddesc: string; public companyid: number; public code: string; public companyname: string; public registrationnumber: string; public companytype: string; public companytypedesc: string; public companylogo: string; public website: string; public phone: string; public email: string; public address1: string; public address2: string; public countryid: number; public countryiddesc: string; public stateid: number; public stateiddesc: string; public cityid: number; public cityiddesc: string; public locationid: number; public locationiddesc: string; public pincode: string; public contactname: string; public designation: number; public designationdesc: string; public cpphone: string; public cpemail: string; public incorporationdate: Date; public businesssegment: string; public businesssegmentdesc: string; public details: string; public services: string; public startdate: Date; public enddate: Date; public bankid: number; public chartofaccounts: number; public shippingaddress1: string; public shippingaddress2: string; public shippingcountryid: number; public shippingcountryiddesc: string; public shippingstateid: number; public shippingstateiddesc: string; public shippingcityid: number; public shippingcityiddesc: string; public shippingpincode: string; public basecurrency: string; public basecurrencydesc: string; public gstregistrationtype: string; public gstregistrationtypedesc: string; public gstinnumber: string; public pannumber: string; public trnnumber: string; public tan: string; public cst: string; public salestax: string; public servicetax: string; public tin: string; public localtax: string; public accountstartdate: Date; public numberofusers: number; public starttime: string; public endtime: string; public weekoff1: string; public weekoff1desc: string; public weekoff2: string; public weekoff2desc: string; public facebookaccountname: string; public facebookaccounturl: string; public twitteraccountname: string; public twitteraccounturl: string; public linkedinaccountname: string; public linkedinaccounturl: string; public instagramaccountname: string; public instagramaccounturl: string; public brandname: string; public mailingemailaddress: string; public mailingsendername: string; public localization: string; public localizationdesc: string; public timezone: string; public timezonedesc: string; public customfield: string; public attachment: string; public status: string; public Deleted_bocompanyholiday_IDs: string; public Deleted_bofinancialyear_IDs: string;
    constructor() { }
}
export interface IbocompanymasterResponse {
    total: number;
    results: bocompanymaster[];
}

