export class bousermaster {
    public useriddesc: string; public userid: number; public sourcefield: string; public sourcereference: number; public userroleid: number; public userroleiddesc: string; public branchid: number; public branchiddesc: string; public departmentid: number; public departmentiddesc: string; public usercode: string; public username: string; public shortname: string; public bio: string; public avatar: string; public designation: number; public designationdesc: string; public reportingto: number; public reportingtodesc: string; public role: number; public roledesc: string; public emailid: string; public mobilenumber: string; public password: string; public nextloginchangepassword: boolean; public validityfrom: Date; public validityto: Date; public educationid: number; public educationiddesc: string; public usersignature: string; public userphoto: string; public thumbnail: string; public emailpassword: string; public emailsignature: string; public dateofbirth: Date; public defaultpage: string; public defaultlanguage: number; public defaultlanguagedesc: string; public layoutpage: string; public theme: string; public gender: string; public genderdesc: string; public nationality: string; public nationalitydesc: string; public bloodgroup: string; public bloodgroupdesc: string; public religion: string; public religiondesc: string; public maritalstatus: string; public maritalstatusdesc: string; public referencenumber: string; public address1: string; public address2: string; public countryid: number; public countryiddesc: string; public stateid: number; public stateiddesc: string; public cityid: number; public cityiddesc: string; public zipcode: string; public emergencycontactperson: string; public relationship: string; public cpphonenumber: string; public emailnotifications: boolean; public whatsappnotifications: boolean; public employeespecificapproval: boolean; public autoapproval: boolean; public approvallevel: number; public approvalleveldesc: string; public approvallevel1: number; public approvallevel1desc: string; public approvallevel2: number; public approvallevel2desc: string; public approvallevel3: number; public approvallevel3desc: string; public approvallevel4: number; public approvallevel4desc: string; public approvallevel5: number; public approvallevel5desc: string; public approvalleveltype1: string; public approvalleveltype1desc: string; public approvalleveltype2: string; public approvalleveltype2desc: string; public approvalleveltype3: string; public approvalleveltype3desc: string; public approvalleveltype4: string; public approvalleveltype4desc: string; public approvalleveltype5: string; public approvalleveltype5desc: string; public twitter: string; public facebook: string; public linkedin: string; public skype: string; public googleplus: string; public customfield: string; public attachment: string; public status: string; public employeeid: number; public Deleted_bousermenuaccess_IDs: string; public Deleted_bouserbranchaccess_IDs: string;
    constructor() { }
}
export interface IbousermasterResponse {
    total: number;
    results: bousermaster[];
}

