export class lmscampaignmaster {
    public productid: number; public productiddesc: string; public campaigniddesc: string; public campaignid: number; public campaigncode: string; public campaignname: string; public campaigntype: string; public campaigntypedesc: string; public campaignowner: string; public validfrom: Date; public validto: Date; public startdate: Date; public enddate: Date; public details: string; public campaignscript: string; public territory: string; public territorydesc: string; public priority: string; public prioritydesc: string; public businessgoal: string; public businessgoaldesc: string; public targetmarket: string; public targetmarketdesc: string; public targetaudience: string; public targetaudiencedesc: string; public targetindustry: string; public targetindustrydesc: string; public strategy: string; public strategydesc: string; public targettype: string; public targettypedesc: string; public expectedofferaction: string; public expectedofferactiondesc: string; public expectedsales: number; public expectedrevenue: number; public expectedprofit: number; public expectedroi: number; public dailytarget: number; public actualachieved: number; public performancestatus: string; public performancestatusdesc: string; public budgetcost: number; public actualcost: number; public mediabudget: number; public actualmediacost: number; public phonenumber: string; public uniquephonenumber: boolean; public landingpage: string; public uniquelandingpage: boolean; public websitelinksavailable: boolean; public numberofpages: number; public enquiryresponsibility: string; public emailresponsibility: string; public campaignemail: string; public trackinboundcalls: boolean; public trackvisitors: boolean; public trackingdetails: string; public handlingvolumes: string; public trainingrequirement: string; public afterenquiry: string; public emailresponsetat: string; public afteremail: string; public customfield: string; public attachment: string; public campaignstatus: string; public campaignstatusdesc: string; public status: string; public Deleted_lmscampaigntask_IDs: string; public Deleted_lmscampaignlocation_IDs: string; public Deleted_lmspost_IDs: string; public Deleted_lmscampaignnoaccess_IDs: string;
    constructor() { }
}
export interface IlmscampaignmasterResponse {
    total: number;
    results: lmscampaignmaster[];
}

