export class lmsopportunity {
    public branchid: number; public leadid: number; public leadiddesc: string; public opportunityiddesc: string; public opportunityid: number; public opportunitydetail: string; public leadby: number; public leadbydesc: string; public opportunitytype: string; public opportunitytypedesc: string; public opportunitystage: number; public opportunitystagedesc: string; public stagesubcategory: number; public stagesubcategorydesc: string; public opportunitysize: string; public opportunitysizedesc: string; public nextstep: string; public nextstepdesc: string; public nextstepdetail: string; public possibilityofclosure: string; public possibilityofclosuredesc: string; public dealvalue: number; public tenderpublishdate: Date; public prebiddate: Date; public submissiondate: Date; public openingdate: Date; public finalopeningdate: Date; public otherdate1: Date; public otherdatenotes1: string; public otherdate2: Date; public otherdatenotes2: string; public otherdate3: Date; public otherdatenotes3: string; public technology: string; public resources: number; public monthlybilling: number; public requirementdetails: string; public leadsource: string; public leadsourcedesc: string; public creationdate: Date; public budget: string; public budgetdesc: string; public tat: string; public actualtat: string; public assignedto: string; public criticality: string; public criticalitydesc: string; public priority: string; public prioritydesc: string; public expectedclosuredate: Date; public expectedvalue: number; public successrate: number; public campaignid: number; public campaigniddesc: string; public notes: string; public attachment: string; public decisionmaker: string; public territory: string; public territorydesc: string; public competitors: string; public winner: string; public reasonforloss: string; public reasonforlossdesc: string; public closeddate: Date; public contactid: number; public lastcontactdate: Date; public status: string; public Deleted_lmsopportunityproduct_IDs: string; public Deleted_lmscall_IDs: string; public Deleted_lmssecondarycontact_IDs: string; public Deleted_lmsreminder_IDs: string; public Deleted_lmsquote_IDs: string; public Deleted_boexpense_IDs: string;
    constructor() { }
}
export interface IlmsopportunityResponse {
    total: number;
    results: lmsopportunity[];
}

