export class camsworkorder {
public workorderiddesc :string;public workorderid :number;public requesttype :string;public requesttypedesc :string;public requestid :number;public requestreference :string;public requestdate :Date;public worktype :string;public worktypedesc :string;public requestorid :number;public requestoriddesc :string;public assetid :number;public assetiddesc :string;public assetstatus :string;public assetstatusdesc :string;public locationid :number;public locationiddesc :string;public sublocationid :number;public sublocationiddesc :string;public details :string;public breakdowndate :Date;public breakdownreported :Date;public reportedby :number;public reportedbydesc :string;public repairstarted :Date;public repaircompleted :Date;public online :Date;public priority :string;public prioritydesc :string;public criticality :string;public criticalitydesc :string;public requireddate :Date;public requestremarks :string;public assetnotes :string;public workpersontype :string;public workpersontypedesc :string;public estimatedworkhrs :string;public actualworkhrs :string;public supplierid :number;public supplieriddesc :string;public suppliername :string;public expirydate :Date;public assignto :string;public username :string;public telephone :string;public mobile :string;public email :string;public startdate :Date;public enddate :Date;public worknotes :string;public query :string;public orderstatus :string;public orderstatusdesc :string;public completionnotes :string;public problem :string;public problemdesc :string;public rootcause :string;public rootcausedesc :string;public solution :string;public solutiondesc :string;public problemdetail :string;public rootcausedetail :string;public solutiondetail :string;public expenseid :number;public expenseiddesc :string;public remarks :string;public customfield :string;public attachment :string;public status :string;public scheduleid :number;public scheduleiddesc :string;public scheduletaskid :number;public scheduletaskiddesc :string;public DeletedcamsworkdetailIDs :string;public DeletedcamsmisccostIDs :string;
constructor() {}
}
export interface IcamsworkorderResponse {
total: number;
results: camsworkorder[];
}

