export class erpitemmaster {
public itemiddesc :string;public itemid :number;public itemcode :string;public type :string;public typedesc :string;public category :number;public categorydesc :string;public subcategory :number;public subcategorydesc :string;public itemgroup :string;public versionnumber :number;public itemshortname :string;public itemname :string;public itemdescription :string;public salesdescription :string;public purchasedescription :string;public brand :string;public thumbnail :string;public alternativeitems :string;public stockuom :string;public stockuomdesc :string;public purchaseuom :string;public purchaseuomdesc :string;public salesuom :string;public salesuomdesc :string;public conversionlogic :string;public itemclass :string;public itemclassdesc :string;public erpcode :string;public trackingmode :string;public trackingmodedesc :string;public qcrequired :boolean;public standardcurrency :string;public standardcost :string;public costmode :string;public costmodedesc :string;public openingstock :number;public valuationrate :number;public valuationmethod :string;public standardsellingrate :number;public isfixedasset :boolean;public depreciationtype :string;public depreciationtypedesc :string;public depreciation :string;public budgetenabled :boolean;public estimatedlife :number;public warrantyexpirydate :Date;public safetystock :string;public reorderpoint :string;public reorderquantity :string;public maximumorderquantity :string;public leadtime :number;public raiseprs :boolean;public purchasetype :string;public purchasetypedesc :string;public materialrequesttype :string;public warehouses :string;public sales :boolean;public lastsaledate :Date;public lastsaleprice :number;public purchase :boolean;public lastpurchasedate :Date;public lastpurchaseprice :number;public workorder :boolean;public batchtracking :boolean;public serialtracking :boolean;public size :string;public color :string;public dimension :string;public width :string;public height :string;public depth :string;public weight :string;public weightuom :string;public weightuomdesc :string;public drawingnumber :string;public attributes :string;public qtyinstock :string;public avgmonthlyconsumption :string;public tax1 :number;public tax2 :number;public tax1value :number;public tax2value :number;public qualityinspectionid :number;public availabledate :Date;public itemstatus :string;public itemstatusdesc :string;public status :string;public DeletederpitemattributeIDs :string;public DeletederpitemimageIDs :string;
constructor() {}
}
export interface IerpitemmasterResponse {
total: number;
results: erpitemmaster[];
}

