export class erppurchaseordermaster {
public branchid :number;public branchiddesc :string;public poiddesc :string;public poid :number;public poname :string;public ponumber :string;public versionnumber :number;public podate :Date;public potype :string;public potypedesc :string;public orderpriority :number;public orderprioritydesc :string;public pocurrency :string;public pocurrencydesc :string;public ourcontactpersonid :number;public ourcontactpersoniddesc :string;public billbranchid :number;public billbranchiddesc :string;public deliverybranchid :number;public deliverybranchiddesc :string;public multicompany :boolean;public supplierid :number;public supplieriddesc :string;public suppliercontactid :number;public suppliercontactiddesc :string;public supplierreference :string;public creditdays :string;public creditdaysdesc :string;public paymentterms :string;public paymenttermsdesc :string;public termsandconditions :string;public tcattachment :string;public shippingdetails :string;public suppliernotes :string;public costcenterid :number;public costcenteriddesc :string;public incoterms :string;public incotermsdesc :string;public reference :string;public expecteddeliverydate :Date;public validenddate :Date;public internalnotes :string;public projectid :number;public projectiddesc :string;public customfield :string;public attachment :string;public vendoracceptance :boolean;public vadate :Date;public supplierquotationid :number;public supplierquotationiddesc :string;public supplierquotationver :number;public totallistprice :number;public discount :number;public totalvalue :number;public shippingcharges :number;public shippingtax :number;public shippingtaxamount :number;public tax :number;public additionaltax :number;public adjustment :number;public poamount :number;public changerequested :string;public supplierchangerequest :string;public postatus :string;public postatusdesc :string;public status :string;public DeletederppurchaseorderdetailIDs :string;public DeletederppurchaseorderpaymenttermIDs :string;
constructor() {}
}
export interface IerppurchaseordermasterResponse {
total: number;
results: erppurchaseordermaster[];
}

