export class erpsupplieritem {
public supplierid :number;public supplieriddesc :string;public supplieritemiddesc :string;public supplieritemid :number;public itemcategoryid :number;public itemcategoryiddesc :string;public itemsubcategoryid :number;public itemsubcategoryiddesc :string;public supplieritemcode :string;public supplierpartname :string;public ourcompanyitemid :number;public ourcompanyitemiddesc :string;public itemdescription :string;public brand :string;public model :string;public make :string;public ispreferred :boolean;public uom :string;public uomdesc :string;public currency :string;public currencydesc :string;public dimensions :string;public producttype :string;public producttypedesc :string;public productimage :string;public description :string;public minorderqty :number;public reorderlevel :number;public leadtimedays :number;public riskclassification :string;public riskclassificationdesc :string;public unitprice :string;public discountpercent :string;public tax1name :number;public tax1namedesc :string;public tax1 :string;public tax2name :number;public tax2namedesc :string;public tax2 :string;public othercharges :string;public totalcost :number;public pricevalidenddate :Date;public offerquantity1 :number;public unitprice1 :number;public totalcost1 :number;public offerquantity2 :number;public unitprice2 :number;public totalcost2 :number;public offerquantity3 :number;public unitprice3 :number;public totalcost3 :number;public availablestock :number;public salesunitsize :string;public salesunitsizedesc :string;public contractid :number;public contractiddesc :string;public suppliercontactid :number;public suppliercontactiddesc :string;public accountid :number;public accountiddesc :string;public remarks :string;public customfield :string;public attachment :string;public status :string;public totalqtyordered :number;public DeletederpsupplieritemfeatureIDs :string;public DeletederpsupplierpaymenttermIDs :string;
constructor() {}
}
export interface IerpsupplieritemResponse {
total: number;
results: erpsupplieritem[];
}

