export class erpsalesordermaster {
public branchid :number;public branchiddesc :string;public soiddesc :string;public soid :number;public sonumber :string;public versionnumber :number;public sodate :Date;public sodetails :string;public customerid :number;public customeriddesc :string;public sotype :string;public sotypedesc :string;public orderpriority :string;public orderprioritydesc :string;public multicompany :boolean;public socurrency :string;public socurrencydesc :string;public ourcontactpersonid :number;public ourcontactpersoniddesc :string;public customercontactid :number;public customercontactiddesc :string;public customerpo :string;public customerpodate :Date;public customerreference :string;public billbranchid :number;public billbranchiddesc :string;public deliverybranchid :number;public deliverybranchiddesc :string;public creditdays :string;public creditdaysdesc :string;public paymentterms :string;public paymenttermsdesc :string;public termsandconditions :string;public tcattachment :string;public shippingdetails :string;public suppliernotes :string;public quotationid :number;public quotationiddesc :string;public quotationver :number;public totallistprice :number;public discount :number;public totalvalue :number;public shippingcharges :number;public shippingtax :number;public shippingtaxamount :number;public tax :number;public soamount :number;public costcenterid :number;public costcenteriddesc :string;public incoterms :string;public incotermsdesc :string;public reference :string;public expecteddeliverydate :Date;public validenddate :Date;public internalnotes :string;public projectid :number;public projectiddesc :string;public customeracceptance :boolean;public customeracceptancedate :Date;public changerequested :string;public customerchangerequest :string;public remarks :string;public orderstatus :string;public orderstatusdesc :string;public leadsource :string;public leadsourcedesc :string;public customfield :string;public attachment :string;public status :string;public DeletederpsalesorderdetailIDs :string;public DeletederpsalesorderpaymenttermIDs :string;
constructor() {}
}
export interface IerpsalesordermasterResponse {
total: number;
results: erpsalesordermaster[];
}

