export class erpsuppliermaster {
public supplieriddesc :string;public supplierid :number;public suppliercode :string;public suppliername :string;public alias :string;public parentsuppliername :string;public thumbnail :string;public industry :string;public industrydesc :string;public companytype :string;public companytypedesc :string;public suppliercategory :number;public suppliercategorydesc :string;public suppliersubcategory :number;public suppliersubcategorydesc :string;public portalid :number;public purchasingtype :string;public purchasingtypedesc :string;public paymentterms :string;public paymenttermsdesc :string;public pomailingtype :string;public pomailingtypedesc :string;public minorderamount :number;public creditlimit :number;public creditnotes :string;public purchasingactivities :string;public creditdays :number;public riskclassification :string;public riskclassificationdesc :string;public tlnumber :string;public tlvalidity :Date;public incorporationdate :Date;public taxregistrationnumber :string;public taxregisteredcountry :number;public taxregisteredcountrydesc :string;public address1 :string;public address2 :string;public country :number;public countrydesc :string;public state :number;public statedesc :string;public city :number;public citydesc :string;public pin :string;public website :string;public telephone :string;public contactperson :string;public designation :string;public mobile :string;public email :string;public directline :string;public assignedto :string;public prequalificationapproved :boolean;public glcode :string;public bankname :string;public accountnumber :string;public accountname :string;public swiftcode :string;public ibannumber :string;public bankaddress1 :string;public bankaddress2 :string;public bankcountry :number;public bankcountrydesc :string;public bankstate :number;public bankstatedesc :string;public bankcity :number;public bankcitydesc :string;public pincode :string;public bankinfonotes :string;public notes :string;public contractid :number;public contractiddesc :string;public suppliedvalue :number;public rejectedvalue :number;public deliveryperiod :number;public delayeddelivery :number;public deliveryrating :number;public qualityrating :number;public status :string;public customfield :string;public attachment :string;public DeletederpsupplierlocationIDs :string;public DeletederpsupplieritemIDs :string;public DeletedboactivityIDs :string;public DeletederpsupplierinvoiceIDs :string;public DeletederpsuppliercertificationIDs :string;public DeletederpsupplierfinancialdataIDs :string;public DeletederpsupplierreferenceIDs :string;
constructor() {}
}
export interface IerpsuppliermasterResponse {
total: number;
results: erpsuppliermaster[];
}

