export class erptendermaster {
public tenderiddesc :string;public tenderid :number;public tenderdate :Date;public title :string;public biddingtype :string;public biddingtypedesc :string;public tendercategory :string;public tendercategorydesc :string;public tendertype :string;public tendertypedesc :string;public biddingsystem :string;public biddingsystemdesc :string;public details :string;public startdate :Date;public enddate :Date;public tenderuploaddate :Date;public prebid :boolean;public prebiddate :Date;public tendervalue :number;public earnestmoney :number;public documentcost :number;public offervaliditydays :number;public completionperiod :number;public completionperiodunit :string;public completionperiodunitdesc :string;public department :number;public departmentdesc :string;public biddingstyle :string;public biddingstyledesc :string;public biddingunit :string;public biddingunitdesc :string;public contracttype :string;public contracttypedesc :string;public jvallowed :boolean;public deliverytime :string;public deliverytimedesc :string;public deliveryterms :string;public deliverytermsdesc :string;public minbidvalue :number;public bidrankingorder :string;public bidrankingorderdesc :string;public responsiblebranchid :number;public responsiblebranchiddesc :string;public deliverybranchid :number;public deliverybranchiddesc :string;public assignedto :string;public visibleall :boolean;public instructions :string;public conditions :string;public prepaidfreight :boolean;public shipcarrier :boolean;public internalnotes :string;public suppliernotes :string;public autoeliminationrule :boolean;public minimumincrement :number;public initialcoolingoffperiod :string;public subsequentcoolingoffperiod :string;public supplierid :number;public supplieriddesc :string;public l1 :number;public l2 :number;public l3 :number;public customfield :string;public attachment :string;public status :string;public DeletederptendercomplianceIDs :string;public DeletederptenderquotationmasterIDs :string;public DeletederptendersupplierresponseIDs :string;public DeletederptenderaccessIDs :string;public DeletederptendercorrigendumIDs :string;public DeletederptenderdetailIDs :string;public DeletederptenderquestionIDs :string;
constructor() {}
}
export interface IerptendermasterResponse {
total: number;
results: erptendermaster[];
}

