export class crmcustomermaster {
public customeriddesc :string;public customerid :number;public basebranchid :number;public basebranchiddesc :string;public customertype :string;public customertypedesc :string;public customergroup :string;public customergroupdesc :string;public categoryid :number;public categoryiddesc :string;public subcategoryid :number;public subcategoryiddesc :string;public territory :number;public territorydesc :string;public customercode :string;public companyname :string;public companytype :string;public companytypedesc :string;public incorporationdate :Date;public businesssegment :string;public businesssegmentdesc :string;public companylogo :string;public thumbnail :string;public website :string;public mobilenumber :string;public officephone :string;public email :string;public metatags :string;public firstname :string;public lastname :string;public gender :string;public genderdesc :string;public dob :Date;public emailid :string;public residencephone :string;public relationshipmanager :number;public relationshipmanagerdesc :string;public address :string;public shippingaddress :string;public billingcurrency :string;public billingcurrencydesc :string;public openingbalance :number;public asondate :Date;public creditdays :number;public creditlimit :number;public accountstartfrom :Date;public servicelevel :number;public slastartdate :Date;public slaenddate :Date;public gstregistrationtype :string;public gstregistrationtypedesc :string;public gstinnumber :string;public pannumber :string;public trnnumber :string;public tan :string;public cst :string;public salestax :string;public servicetax :string;public tin :string;public localtax :string;public itfilings :string;public lifetimevalue :number;public averageordervalue :number;public totalorders :number;public totalordervalue :number;public lastorderdate :Date;public lastordervalue :number;public loyaltynumber :string;public pointsearned :number;public activepoints :number;public usedpoints :number;public expiredpoints :number;public lockedpoints :number;public blockedpoints :number;public pointsearnedincurrency :number;public activepointsincurrency :number;public usedpointsincurrency :number;public expiredpointsincurrency :number;public lockedpointsincurrency :number;public blockedpointsincurrency :number;public allocationmethod :string;public allocationmethoddesc :string;public customfield :string;public attachment :string;public cifnumber :string;public outstandingamt :number;public status :string;public DeletedcrmcustomeraccountmasterIDs :string;public DeletedltycustomerrewardIDs :string;public DeletedecmcustomerbasketIDs :string;public DeletedboauditeventsIDs :string;public DeletedcrmcustomerkycmasterIDs :string;public DeletedecmreviewIDs :string;
constructor() {}
}
export interface IcrmcustomermasterResponse {
total: number;
results: crmcustomermaster[];
}

